"""
Script to create a more comprehensive German dictionary for the pronunciation assessment service.
"""
import os
import logging
from pathlib import Path

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Additional German words with phoneme transcriptions (IPA)
# This extends our existing fallback dictionary with more common German words
ADDITIONAL_GERMAN_WORDS = {
    # Common verbs
    "arbeiten": ["a", "ʁ", "b", "aɪ", "t", "ə", "n"],
    "beginnen": ["b", "ə", "g", "ɪ", "n", "ə", "n"],
    "besuchen": ["b", "ə", "z", "u:", "x", "ə", "n"],
    "bezahlen": ["b", "ə", "ts", "a:", "l", "ə", "n"],
    "brauchen": ["b", "ʁ", "aʊ", "x", "ə", "n"],
    "bringen": ["b", "ʁ", "ɪ", "ŋ", "ə", "n"],
    "dauern": ["d", "aʊ", "ɐ", "n"],
    "denken": ["d", "ɛ", "ŋ", "k", "ə", "n"],
    "essen": ["ɛ", "s", "ə", "n"],
    "fahren": ["f", "a:", "ʁ", "ə", "n"],
    "fallen": ["f", "a", "l", "ə", "n"],
    "finden": ["f", "ɪ", "n", "d", "ə", "n"],
    "fliegen": ["f", "l", "i:", "g", "ə", "n"],
    "folgen": ["f", "ɔ", "l", "g", "ə", "n"],
    "fragen": ["f", "ʁ", "a:", "g", "ə", "n"],
    "geben": ["g", "e:", "b", "ə", "n"],
    "gefallen": ["g", "ə", "f", "a", "l", "ə", "n"],
    "gehen": ["g", "e:", "ə", "n"],
    "gehören": ["g", "ə", "h", "ø:", "ʁ", "ə", "n"],
    "gewinnen": ["g", "ə", "v", "ɪ", "n", "ə", "n"],
    "glauben": ["g", "l", "aʊ", "b", "ə", "n"],
    "haben": ["h", "a:", "b", "ə", "n"],
    "halten": ["h", "a", "l", "t", "ə", "n"],
    "heißen": ["h", "aɪ", "s", "ə", "n"],
    "helfen": ["h", "ɛ", "l", "f", "ə", "n"],
    "hören": ["h", "ø:", "ʁ", "ə", "n"],
    "kaufen": ["k", "aʊ", "f", "ə", "n"],
    "kennen": ["k", "ɛ", "n", "ə", "n"],
    "kommen": ["k", "ɔ", "m", "ə", "n"],
    "können": ["k", "œ", "n", "ə", "n"],
    "kosten": ["k", "ɔ", "s", "t", "ə", "n"],
    "lassen": ["l", "a", "s", "ə", "n"],
    "laufen": ["l", "aʊ", "f", "ə", "n"],
    "leben": ["l", "e:", "b", "ə", "n"],
    "legen": ["l", "e:", "g", "ə", "n"],
    "lernen": ["l", "ɛ", "ʁ", "n", "ə", "n"],
    "lesen": ["l", "e:", "z", "ə", "n"],
    "lieben": ["l", "i:", "b", "ə", "n"],
    "liegen": ["l", "i:", "g", "ə", "n"],
    "machen": ["m", "a", "x", "ə", "n"],
    "mögen": ["m", "ø:", "g", "ə", "n"],
    "müssen": ["m", "ʏ", "s", "ə", "n"],
    "nehmen": ["n", "e:", "m", "ə", "n"],
    "nennen": ["n", "ɛ", "n", "ə", "n"],
    "öffnen": ["œ", "f", "n", "ə", "n"],
    "passieren": ["p", "a", "s", "i:", "ʁ", "ə", "n"],
    "reisen": ["ʁ", "aɪ", "z", "ə", "n"],
    "rufen": ["ʁ", "u:", "f", "ə", "n"],
    "sagen": ["z", "a:", "g", "ə", "n"],
    "schauen": ["ʃ", "aʊ", "ə", "n"],
    "scheinen": ["ʃ", "aɪ", "n", "ə", "n"],
    "schlafen": ["ʃ", "l", "a:", "f", "ə", "n"],
    "schließen": ["ʃ", "l", "i:", "s", "ə", "n"],
    "schmecken": ["ʃ", "m", "ɛ", "k", "ə", "n"],
    "schreiben": ["ʃ", "ʁ", "aɪ", "b", "ə", "n"],
    "schwimmen": ["ʃ", "v", "ɪ", "m", "ə", "n"],
    "sehen": ["z", "e:", "ə", "n"],
    "sein": ["z", "aɪ", "n"],
    "setzen": ["z", "ɛ", "ts", "ə", "n"],
    "singen": ["z", "ɪ", "ŋ", "ə", "n"],
    "sitzen": ["z", "ɪ", "ts", "ə", "n"],
    "sollen": ["z", "ɔ", "l", "ə", "n"],
    "spielen": ["ʃ", "p", "i:", "l", "ə", "n"],
    "sprechen": ["ʃ", "p", "ʁ", "ɛ", "ç", "ə", "n"],
    "stehen": ["ʃ", "t", "e:", "ə", "n"],
    "steigen": ["ʃ", "t", "aɪ", "g", "ə", "n"],
    "sterben": ["ʃ", "t", "ɛ", "ʁ", "b", "ə", "n"],
    "stimmen": ["ʃ", "t", "ɪ", "m", "ə", "n"],
    "suchen": ["z", "u:", "x", "ə", "n"],
    "tragen": ["t", "ʁ", "a:", "g", "ə", "n"],
    "treffen": ["t", "ʁ", "ɛ", "f", "ə", "n"],
    "tun": ["t", "u:", "n"],
    "vergessen": ["f", "ɛ", "ʁ", "g", "ɛ", "s", "ə", "n"],
    "verkaufen": ["f", "ɛ", "ʁ", "k", "aʊ", "f", "ə", "n"],
    "verstehen": ["f", "ɛ", "ʁ", "ʃ", "t", "e:", "ə", "n"],
    "warten": ["v", "a", "ʁ", "t", "ə", "n"],
    "waschen": ["v", "a", "ʃ", "ə", "n"],
    "werden": ["v", "e:", "ʁ", "d", "ə", "n"],
    "wissen": ["v", "ɪ", "s", "ə", "n"],
    "wohnen": ["v", "o:", "n", "ə", "n"],
    "wollen": ["v", "ɔ", "l", "ə", "n"],
    "zahlen": ["ts", "a:", "l", "ə", "n"],
    "zeigen": ["ts", "aɪ", "g", "ə", "n"],
    "ziehen": ["ts", "i:", "ə", "n"],
    "zuhören": ["ts", "u:", "h", "ø:", "ʁ", "ə", "n"],
    
    # Common nouns
    "auto": ["aʊ", "t", "o:"],
    "bahn": ["b", "a:", "n"],
    "buch": ["b", "u:", "x"],
    "büro": ["b", "y:", "ʁ", "o:"],
    "computer": ["k", "ɔ", "m", "p", "j", "u:", "t", "ɐ"],
    "familie": ["f", "a", "m", "i:", "l", "i", "ə"],
    "fenster": ["f", "ɛ", "n", "s", "t", "ɐ"],
    "flughafen": ["f", "l", "u:", "k", "h", "a:", "f", "ə", "n"],
    "frau": ["f", "ʁ", "aʊ"],
    "freund": ["f", "ʁ", "ɔɪ", "n", "t"],
    "freundin": ["f", "ʁ", "ɔɪ", "n", "d", "ɪ", "n"],
    "geld": ["g", "ɛ", "l", "t"],
    "geschichte": ["g", "ə", "ʃ", "ɪ", "ç", "t", "ə"],
    "gesundheit": ["g", "ə", "z", "ʊ", "n", "t", "h", "aɪ", "t"],
    "haus": ["h", "aʊ", "s"],
    "herr": ["h", "ɛ", "ʁ"],
    "hotel": ["h", "o", "t", "ɛ", "l"],
    "idee": ["i", "d", "e:"],
    "jahr": ["j", "a:", "ʁ"],
    "kind": ["k", "ɪ", "n", "t"],
    "klasse": ["k", "l", "a", "s", "ə"],
    "konzert": ["k", "ɔ", "n", "ts", "ɛ", "ʁ", "t"],
    "küche": ["k", "ʏ", "ç", "ə"],
    "land": ["l", "a", "n", "t"],
    "leben": ["l", "e:", "b", "ə", "n"],
    "leute": ["l", "ɔɪ", "t", "ə"],
    "lied": ["l", "i:", "t"],
    "mann": ["m", "a", "n"],
    "maschine": ["m", "a", "ʃ", "i:", "n", "ə"],
    "meer": ["m", "e:", "ʁ"],
    "mensch": ["m", "ɛ", "n", "ʃ"],
    "minute": ["m", "i", "n", "u:", "t", "ə"],
    "monat": ["m", "o:", "n", "a", "t"],
    "name": ["n", "a:", "m", "ə"],
    "nummer": ["n", "ʊ", "m", "ɐ"],
    "platz": ["p", "l", "a", "ts"],
    "problem": ["p", "ʁ", "o", "b", "l", "e:", "m"],
    "programm": ["p", "ʁ", "o", "g", "ʁ", "a", "m"],
    "radio": ["ʁ", "a:", "d", "i", "o:"],
    "restaurant": ["ʁ", "ɛ", "s", "t", "o", "ʁ", "a:"],
    "schule": ["ʃ", "u:", "l", "ə"],
    "sohn": ["z", "o:", "n"],
    "sommer": ["z", "ɔ", "m", "ɐ"],
    "sonne": ["z", "ɔ", "n", "ə"],
    "sprache": ["ʃ", "p", "ʁ", "a:", "x", "ə"],
    "stadt": ["ʃ", "t", "a", "t"],
    "stunde": ["ʃ", "t", "ʊ", "n", "d", "ə"],
    "tag": ["t", "a:", "k"],
    "telefon": ["t", "e", "l", "e", "f", "o:", "n"],
    "tisch": ["t", "ɪ", "ʃ"],
    "tochter": ["t", "ɔ", "x", "t", "ɐ"],
    "tür": ["t", "y:", "ʁ"],
    "uhr": ["u:", "ʁ"],
    "universität": ["u", "n", "i", "v", "ɛ", "ʁ", "z", "i", "t", "ɛ:", "t"],
    "vater": ["f", "a:", "t", "ɐ"],
    "wasser": ["v", "a", "s", "ɐ"],
    "welt": ["v", "ɛ", "l", "t"],
    "winter": ["v", "ɪ", "n", "t", "ɐ"],
    "woche": ["v", "ɔ", "x", "ə"],
    "wohnung": ["v", "o:", "n", "ʊ", "ŋ"],
    "zeit": ["ts", "aɪ", "t"],
    "zimmer": ["ts", "ɪ", "m", "ɐ"],
    "zug": ["ts", "u:", "k"],
    
    # Common adjectives
    "alt": ["a", "l", "t"],
    "andere": ["a", "n", "d", "ə", "ʁ", "ə"],
    "bekannt": ["b", "ə", "k", "a", "n", "t"],
    "bereit": ["b", "ə", "ʁ", "aɪ", "t"],
    "besser": ["b", "ɛ", "s", "ɐ"],
    "billig": ["b", "ɪ", "l", "ɪ", "ç"],
    "böse": ["b", "ø:", "z", "ə"],
    "deutlich": ["d", "ɔɪ", "t", "l", "ɪ", "ç"],
    "direkt": ["d", "i", "ʁ", "ɛ", "k", "t"],
    "dunkel": ["d", "ʊ", "ŋ", "k", "ə", "l"],
    "einfach": ["aɪ", "n", "f", "a", "x"],
    "einzeln": ["aɪ", "n", "ts", "ə", "l", "n"],
    "eng": ["ɛ", "ŋ"],
    "froh": ["f", "ʁ", "o:"],
    "früh": ["f", "ʁ", "y:"],
    "ganz": ["g", "a", "n", "ts"],
    "genau": ["g", "ə", "n", "aʊ"],
    "gesund": ["g", "ə", "z", "ʊ", "n", "t"],
    "groß": ["g", "ʁ", "o:", "s"],
    "gut": ["g", "u:", "t"],
    "heiß": ["h", "aɪ", "s"],
    "hell": ["h", "ɛ", "l"],
    "herzlich": ["h", "ɛ", "ʁ", "ts", "l", "ɪ", "ç"],
    "hoch": ["h", "o:", "x"],
    "hübsch": ["h", "ʏ", "p", "ʃ"],
    "jung": ["j", "ʊ", "ŋ"],
    "kalt": ["k", "a", "l", "t"],
    "klar": ["k", "l", "a:", "ʁ"],
    "klein": ["k", "l", "aɪ", "n"],
    "klug": ["k", "l", "u:", "k"],
    "kurz": ["k", "ʊ", "ʁ", "ts"],
    "lang": ["l", "a", "ŋ"],
    "langsam": ["l", "a", "ŋ", "z", "a", "m"],
    "laut": ["l", "aʊ", "t"],
    "leicht": ["l", "aɪ", "ç", "t"],
    "leise": ["l", "aɪ", "z", "ə"],
    "letzt": ["l", "ɛ", "ts", "t"],
    "lieb": ["l", "i:", "p"],
    "lustig": ["l", "ʊ", "s", "t", "ɪ", "ç"],
    "müde": ["m", "y:", "d", "ə"],
    "möglich": ["m", "ø:", "k", "l", "ɪ", "ç"],
    "natürlich": ["n", "a", "t", "y:", "ʁ", "l", "ɪ", "ç"],
    "nett": ["n", "ɛ", "t"],
    "neu": ["n", "ɔɪ"],
    "normal": ["n", "ɔ", "ʁ", "m", "a:", "l"],
    "offen": ["ɔ", "f", "ə", "n"],
    "oft": ["ɔ", "f", "t"],
    "praktisch": ["p", "ʁ", "a", "k", "t", "ɪ", "ʃ"],
    "richtig": ["ʁ", "ɪ", "ç", "t", "ɪ", "ç"],
    "ruhig": ["ʁ", "u:", "ɪ", "ç"],
    "rund": ["ʁ", "ʊ", "n", "t"],
    "sauber": ["z", "aʊ", "b", "ɐ"],
    "schlecht": ["ʃ", "l", "ɛ", "ç", "t"],
    "schnell": ["ʃ", "n", "ɛ", "l"],
    "schön": ["ʃ", "ø:", "n"],
    "schwer": ["ʃ", "v", "e:", "ʁ"],
    "stark": ["ʃ", "t", "a", "ʁ", "k"],
    "still": ["ʃ", "t", "ɪ", "l"],
    "süß": ["z", "y:", "s"],
    "teuer": ["t", "ɔɪ", "ɐ"],
    "tief": ["t", "i:", "f"],
    "toll": ["t", "ɔ", "l"],
    "tot": ["t", "o:", "t"],
    "typisch": ["t", "y:", "p", "ɪ", "ʃ"],
    "üblich": ["y:", "p", "l", "ɪ", "ç"],
    "viel": ["f", "i:", "l"],
    "warm": ["v", "a", "ʁ", "m"],
    "wichtig": ["v", "ɪ", "ç", "t", "ɪ", "ç"],
    "wunderbar": ["v", "ʊ", "n", "d", "ɐ", "b", "a:", "ʁ"],
}

# Original Fallback Dictionary
ORIGINAL_FALLBACK = {
    "hallo": ["h", "a", "l", "o"],
    "ich": ["ɪ", "ç"],
    "spreche": ["ʃ", "p", "ʁ", "ɛ", "ç", "ə"],
    "deutsch": ["d", "ɔ", "y", "t", "ʃ"],
    "wie": ["v", "i:"],
    "geht": ["g", "e:", "t"],
    "es": ["ɛ", "s"],
    "ihnen": ["i:", "n", "ə", "n"],
    "gut": ["g", "u:", "t"],
    "danke": ["d", "a", "ŋ", "k", "ə"],
    "bitte": ["b", "ɪ", "t", "ə"],
    "ja": ["j", "a:"],
    "nein": ["n", "aɪ", "n"],
    "tag": ["t", "a:", "k"],
    "guten": ["g", "u:", "t", "ə", "n"],
    "morgen": ["m", "ɔ", "ʁ", "g", "ə", "n"],
    "abend": ["a:", "b", "ə", "n", "t"],
    "nacht": ["n", "a", "x", "t"],
    "schön": ["ʃ", "ø:", "n"],
    "tschüss": ["tʃ", "ʏ", "s"],
    "auf": ["aʊ", "f"],
    "wiedersehen": ["v", "i:", "d", "ɐ", "z", "e:", "ə", "n"],
    "bald": ["b", "a", "l", "t"],
    "später": ["ʃ", "p", "ɛ:", "t", "ɐ"],
    "heute": ["h", "ɔɪ", "t", "ə"],
    "woche": ["v", "ɔ", "x", "ə"],
    "monat": ["m", "o:", "n", "a", "t"],
    "jahr": ["j", "a:", "ʁ"],
    "zeit": ["ts", "aɪ", "t"],
    "uhr": ["u:", "ʁ"],
    "stunde": ["ʃ", "t", "ʊ", "n", "d", "ə"],
    "minute": ["m", "i", "n", "u:", "t", "ə"],
    "sekunde": ["z", "e", "k", "ʊ", "n", "d", "ə"],
    "wasser": ["v", "a", "s", "ɐ"],
    "brot": ["b", "ʁ", "o:", "t"],
    "käse": ["k", "ɛ:", "z", "ə"],
    "fleisch": ["f", "l", "aɪ", "ʃ"],
    "gemüse": ["g", "ə", "m", "y:", "z", "ə"],
    "obst": ["o:", "p", "s", "t"],
    "apfel": ["a", "p", "f", "ə", "l"],
    "banane": ["b", "a", "n", "a:", "n", "ə"],
    "orange": ["o", "ʁ", "a", "n", "ʒ", "ə"],
    "erdbeere": ["e:", "ʁ", "t", "b", "e:", "ʁ", "ə"],
    "himbeere": ["h", "ɪ", "m", "b", "e:", "ʁ", "ə"],
    "blaubeere": ["b", "l", "aʊ", "b", "e:", "ʁ", "ə"],
    "kaffee": ["k", "a", "f", "e:"],
    "tee": ["t", "e:"],
    "milch": ["m", "ɪ", "l", "ç"],
    "zucker": ["ts", "ʊ", "k", "ɐ"],
    "salz": ["z", "a", "l", "ts"],
    "pfeffer": ["p", "f", "ɛ", "f", "ɐ"],
    "sein": ["z", "aɪ", "n"],
    "haben": ["h", "a:", "b", "ə", "n"],
    "können": ["k", "œ", "n", "ə", "n"],
    "mögen": ["m", "ø:", "g", "ə", "n"],
    "pontecan": ["p", "o", "n", "t", "e", "c", "a", "n"],
    "einigermaßen": ["aɪ", "n", "i", "g", "ɐ", "m", "a:", "s", "ə", "n"],
    # Adding more common German words
    "und": ["ʊ", "n", "t"],
    "der": ["d", "e:", "ɐ"],
    "die": ["d", "i:"],
    "das": ["d", "a", "s"],
    "ein": ["aɪ", "n"],
    "eine": ["aɪ", "n", "ə"],
    "zu": ["ts", "u:"],
    "von": ["f", "ɔ", "n"],
    "mit": ["m", "ɪ", "t"],
    "für": ["f", "y:", "ɐ"],
    "ist": ["ɪ", "s", "t"],
    "sind": ["z", "ɪ", "n", "t"],
    "war": ["v", "a:", "ɐ"],
    "waren": ["v", "a:", "ʁ", "ə", "n"],
    "werden": ["v", "e:", "ɐ", "d", "ə", "n"],
    "wurde": ["v", "ʊ", "ʁ", "d", "ə"],
    "wurden": ["v", "ʊ", "ʁ", "d", "ə", "n"],
    "machen": ["m", "a", "x", "ə", "n"],
    "sagen": ["z", "a:", "g", "ə", "n"],
    "gehen": ["g", "e:", "ə", "n"],
    "sehen": ["z", "e:", "ə", "n"],
    "kommen": ["k", "ɔ", "m", "ə", "n"],
    "nehmen": ["n", "e:", "m", "ə", "n"],
    "wissen": ["v", "ɪ", "s", "ə", "n"],
    "kennen": ["k", "ɛ", "n", "ə", "n"],
    "denken": ["d", "ɛ", "ŋ", "k", "ə", "n"],
    "glauben": ["g", "l", "aʊ", "b", "ə", "n"],
    "finden": ["f", "ɪ", "n", "d", "ə", "n"],
    "fehlen": ["f", "e:", "l", "ə", "n"],
    "lieben": ["l", "i:", "b", "ə", "n"],
    "leben": ["l", "e:", "b", "ə", "n"],
    "bleiben": ["b", "l", "aɪ", "b", "ə", "n"],
    "geben": ["g", "e:", "b", "ə", "n"],
    "lassen": ["l", "a", "s", "ə", "n"],
    "tun": ["t", "u:", "n"],
    "machen": ["m", "a", "x", "ə", "n"],
    "heiße": ["h", "aɪ", "s", "ə"],
}

def main():
    """
    Creates an expanded German dictionary by combining the original fallback dictionary
    with additional German words.
    """
    # Create dictionary directory if it doesn't exist
    dict_dir = Path("mfa_models/dictionaries")
    os.makedirs(dict_dir, exist_ok=True)
    
    # Path to the German dictionary
    dict_path = dict_dir / "german_mfa.dict"
    
    # Combine dictionaries
    combined_dict = {**ORIGINAL_FALLBACK, **ADDITIONAL_GERMAN_WORDS}
    
    # Sort the dictionary by word
    sorted_dict = dict(sorted(combined_dict.items()))
    
    # Count words in each dictionary
    original_count = len(ORIGINAL_FALLBACK)
    additional_count = len(ADDITIONAL_GERMAN_WORDS)
    combined_count = len(combined_dict)
    
    logger.info(f"Original dictionary: {original_count} words")
    logger.info(f"Additional words: {additional_count} words")
    logger.info(f"Combined dictionary: {combined_count} words")
    
    # Write the dictionary to file
    with open(dict_path, 'w', encoding='utf-8') as f:
        f.write("# German pronunciation dictionary\n")
        f.write(f"# Combined dictionary with {combined_count} words\n")
        
        for word, phonemes in sorted_dict.items():
            # Format phonemes with spaces between them
            phoneme_str = ' '.join(phonemes)
            f.write(f"{word}\t{phoneme_str}\n")
    
    logger.info(f"Dictionary written to {dict_path}")
    logger.info(f"Dictionary size: {os.path.getsize(dict_path)} bytes")

if __name__ == "__main__":
    main() 